indicators/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndicatorListView.as_view(), name='index'),
    url(r'^create/$', views.IndicatorCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/update$', views.IndicatorUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete$', views.IndicatorDeleteView.as_view(), name='delete'),
    url(r'^search/$', views.IndicatorSearchView.as_view(), name='search'),
]

sgpp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^project/', include('projects.urls', namespace='project')),
    url(r'^indicator/', include('indicators.urls', namespace='indicator')),
    url(r'^report/', include('reports.urls', namespace='report')),
    url(r'^admin/', admin.site.urls),
]

indicators/models.py
from django.db import models
from django.db.models import Q
# Create your models here.


class IndicatorQuerySet(models.query.QuerySet):

    def search(self, query):
        lookups = (
            Q(name__icontains=query)
        )
        return self.filter(lookups, is_active=True).distinct()


class IndicatorManager(models.Manager):

    def get_queryset(self):
        return IndicatorQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class Indicator(models.Model):
    """
    O sistema deve permitir o cadastro de indicadores (inserção, exclusão, alteração e consulta). Cada indicador
    deve ter um nome.
    """

    name = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=True)

    objects = IndicatorManager()

    def __str__(self):
        return self.name

indicators/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Indicator


class NewIndicatorForm(forms.ModelForm):
    #Formulário de cadastro de um novo indicador
    class Meta:
        model = Indicator
        fields = ['name',]
        labels = { 'name': ('Nome'), }

    
    def clean_name(self):
        cleaned_data = super(NewIndicatorForm, self).clean()

        data = cleaned_data.get('name')

        n = Indicator.objects.filter(name=data)

        if n.exists():
            raise forms.ValidationError('Este nome já está sendo usado.')

        return data


class UpdateIndicatorForm(forms.ModelForm):

    class Meta:
        model = Indicator
        fields = ['name',]
        labels = { 'name': ('Nome'), }

    def clean_name(self):
        cleaned_data = super(UpdateIndicatorForm, self).clean()

        data = cleaned_data.get('name')

        n = Indicator.objects.filter(name=data)

        if n.exists():
            raise forms.ValidationError('Este nome já está sendo usado.')

        return data

indicators/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import (
    ListView, CreateView, DetailView, UpdateView, DeleteView, FormView)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import (LoginRequiredMixin,)
from django.contrib.auth.models import Group
from django.contrib import messages
from django.template.loader import render_to_string

from .models import Indicator
from .forms import NewIndicatorForm, UpdateIndicatorForm

# Create your views here.


def has_group(user, group_name):
    group = Group.objects.get(name=group_name)
    return True if group in user.groups.all() else False


class IndicatorListView(LoginRequiredMixin, ListView):
    
    model = Indicator
    template_name = 'indicators/indicator_list.html'
    context_object_name = 'indicator_list'
    paginate_by = 10

    def get_queryset(self):
        return Indicator.objects.filter(is_active=True).order_by('name')


class IndicatorSearchView(LoginRequiredMixin, ListView):
    
    model = Indicator
    template_name = 'indicators/indicator_list.html'
    context_object_name = 'indicator_list'

    def get_context_data(self, *args, **kwargs):
    	context = super(IndicatorSearchView, self).get_context_data(*args, **kwargs)
    	context['query'] = self.request.GET.get('q')
    	return context

    def get_queryset(self, *args, **kwargs):
        request = self.request
        query = request.GET.get('q')

        if query is not None:
            return Indicator.objects.search(query)
        return Indicator.objects.none()


class IndicatorCreateView(LoginRequiredMixin, CreateView):

    model = Indicator
    success_url = '/indicator/'
    template_name = 'indicators/indicator_form.html'
    form_class = NewIndicatorForm

    def get(self, request, *args, **kwargs):

        if has_group(request.user, 'pmo_leader'):
            return super(IndicatorCreateView, self).get(request, *args, **kwargs)
        else:
            messages.error(
                request, 'Apenas o Lider do Escritório de Projetos pode cadastrar um novo Indicador.')
            return redirect(reverse('indicator:index'))

    def form_valid(self, form):
        messages.success(self.request, 'Indicador cadastrado com sucesso.')
        return super(IndicatorCreateView, self).form_valid(form)


class IndicatorUpdateView(LoginRequiredMixin, UpdateView):

    model = Indicator
    form_class = UpdateIndicatorForm
    template_name = 'indicators/indicator_update.html'
    success_url = '/indicator/'

    def get(self, request, *args, **kwargs):

        if has_group(request.user, 'pmo_leader'):
            return super(IndicatorUpdateView, self).get(request, *args, **kwargs)
        else:
            messages.error(request, 'Apenas o Lider do Escritório de Projetos pode atualizar o Indicador.')
            return redirect(reverse('indicator:index'))
    
    def form_valid(self, form):
        messages.success(self.request, 'Indicador alterado com sucesso.')
        return super(IndicatorUpdateView, self).form_valid(form)


class IndicatorDeleteView(LoginRequiredMixin, DeleteView):

    model = Indicator
    template_name = 'indicators/indicator_delete.html'
    success_url = '/indicator/'

    def get(self, request, *args, **kwargs):

        if has_group(request.user, 'pmo_leader'):
            return super(IndicatorDeleteView, self).get(request, *args, **kwargs)
        else:
            messages.error(request, 'Apenas o Lider do Escritório de Projetos pode excluir o Indicador.')
            return redirect(reverse('indicator:index'))

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Indicador excluído com sucesso.')
        return super(IndicatorDeleteView, self).delete(request, *args, **kwargs)

indicators/templates/indicators/indicator_delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Indicadores{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item active">Excluir Indicador</li>
{% endblock %} 

{% block content %}

<form method="post">
    {% csrf_token %}
    <h4>Excluir Indicador?</h4>
    <p>Deseja realmente excluir o indicador? <strong>{{ indicator.name }}</strong></p>
    <button type="submit" class="btn btn-danger">Excluir</button>
</form>
{% endblock %}

indicators/templates/indicators/indicator_form.html
{% extends 'base.html' %} 

{% load widget_tweaks %}

{% block title %}Novo Indicador{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item">
  <a href="{% url 'indicator:index' %}">Indicadores</a>
</li>
<li class="breadcrumb-item active">Novo Indicador</li>
{% endblock %} 

{% block content %}
<form method="post" novalidate>
  {% csrf_token %} 
  
  {% include 'includes/form.html' %}
  <a class="btn btn-primary" href="{% url 'indicator:index' %}">Voltar</a>
  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
{% endblock %}

indicators/templates/indicators/indicator_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Indicadores{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item active">Indicadores</li>
{% endblock %} 

{% block content %}

<div class="mb-2 float-left">
    <a class="btn btn-success" href="{% url 'indicator:create' %}">Adicionar Indicador</a>
</div>

<div class="mb-2 float-right">
    <form class="form-inline my-lg-0" action="{% url 'indicator:search' %}" method="GET">
        <input class="form-control mr-sm-2" type="text" placeholder="Pesquisar" aria-label="Search" name="q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
</div>

<table class="table table-striped table-responsive-sm" id="indicator-table">
    <thead class="thead-dark">
        <tr>
            <th>Indicador</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        {% include 'indicators/includes/partial_indicator_list.html' %}           
    </tbody>
</table>

{% include 'includes/pagination.html' %}

{% endblock %}

indicators/templates/indicators/indicator_update.html
{% extends 'base.html' %} 

{% load widget_tweaks %}

{% block title %}Novo Indicador{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item">
  <a href="{% url 'indicator:index' %}">Indicadores</a>
</li>
<li class="breadcrumb-item active">Atualizar Indicador</li>
{% endblock %} 

{% block content %}
<form method="post" novalidate>
  {% csrf_token %} 
  
  {% include 'includes/form.html' %}

  <button type="submit" class="btn btn-success">Atualizar</button>
</form>
{% endblock %}