projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.ProjectListView.as_view(), name='index'),
    url(r'create/$', views.ProjectCreateView.as_view(), name='create'),
    url(r'(?P<pk>\d+)/detail$', views.ProjectDetailView.as_view(), name='detail'),
    url(r'(?P<pk>\d+)/update$', views.ProjectUpdateView.as_view(), name='update'),
    url(r'(?P<pk>\d+)/delete$', views.ProjectDeleteView.as_view(), name='delete'),
    url(r'^search/$', views.ProjectSearchView.as_view(), name='search'),

    url(r'(?P<pk>\d+)/add/followup$', views.project_add_followup, name='add_follow_up'),

    url(r'(?P<pk>\d+)/add/member$', views.project_add_member, name='add_member'),
    url(r'(?P<pk>\d+)/delete/member$', views.ProjectMemberDeleteView.as_view(), name='delete_member'),

    url(r'(?P<pk>\d+)/connect/indicator$', views.project_connect_indicator, name='connect_indicator'),
    url(r'(?P<pk>\d+)/inform/indicator$', views.project_inform_indicator, name='inform_indicator'),
    
    url(r'(?P<pk>\d+)/add/activity$', views.project_add_activity, name='add_activity'),
    url(r'(?P<pk>\d+)/delete/activity$', views.ProjectActivityDeleteView.as_view(), name='delete_activity'),

    url(r'(?P<pk>\d+)/change/status$', views.project_change_status, name='change_status'),
    url(r'(?P<pk>\d+)/cancel$', views.project_cancel, name='cancel'),
]

sgpp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^project/', include('projects.urls', namespace='project')),
    url(r'^indicator/', include('indicators.urls', namespace='indicator')),
    url(r'^report/', include('reports.urls', namespace='report')),
    url(r'^admin/', admin.site.urls),
]

activities/models.py
from django.db import models
from projects.models import Project
from django.core.validators import MinValueValidator
from decimal import Decimal

# Create your models here.
class Activity(models.Model):
    """
    Permite gerenciar (Inserir, Excluir, Alterar, Consultar) as atividades que serão desempenhadas no projeto,
    deve ser informado um nome e descricao ao associar ao projeto.
    """

    name = models.CharField(max_length=50)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='activities')

    """
    O orçamento da atividade deve obedecer o limite máximo do orçamento restante do projeto
    """
    budget = models.DecimalField(max_digits=9, decimal_places=2, validators=[MinValueValidator(Decimal('0.01'))])

    def __str__(self):
        return self.name

projects/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.utils import timezone

from indicators.models import Indicator

# Create your models here.
User = get_user_model()


class ProjectQuerySet(models.query.QuerySet):

    def active(self):
        return self.exclude(status=8).order_by('rating','-start_date')

    def search(self, query):
        lookups = (
            Q(manager__username__icontains=query) |
            Q(name__icontains=query)
        )
        return self.filter(lookups).distinct()


class ProjectManager(models.Manager):

    def get_queryset(self):
        return ProjectQuerySet(self.model, using=self._db)

    def search(self, query):
        return self.get_queryset().search(query)


class Project(models.Model):

    """
    O sistema deve permitir o cadastro (inserção, exclusão, alteração e consulta) de projetos. Para cada projeto
    devem ser informados: nome, data de início, gerente responsável, previsão de término, data real de
    término, orçamento total, descrição e status. Os projetos devem ser classificados em: baixo risco, médio
    risco e alto risco. A classificação de risco não é cadastrada no sistema. Os status possíveis não são
    cadastrados no sistema. Os status possíveis são: em análise, análise realizada, análise aprovada, iniciado,
    planejado, em andamento, encerrado, cancelado.
    """

    STATUS_CHOICES = (
        (1, 'Em Análise'),
        (2, 'Análise Realizada'),
        (3, 'Análise Aprovada'),
        (4, 'Iniciado'),
        (5, 'Planejado'),
        (6, 'Em Andamento'),
        (7, 'Encerrado'),
        (8, 'Cancelado'),
    )

    RATING_CHOICES = (
        (1, 'Baixo'),
        (2, 'Médio'),
        (3, 'Alto'),
    )

    name = models.CharField(max_length=140)
    description = models.TextField()
    manager = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='manager')
    leader = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='leader')
    start_date = models.DateField()
    forecast_finish_date = models.DateField()
    end_date = models.DateField(null=True)
    budget = models.DecimalField(max_digits=9, decimal_places=2, validators=[
                                 MinValueValidator(Decimal('0.01'))])
    status = models.PositiveSmallIntegerField(
        choices=STATUS_CHOICES, default=1)
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)
    modified = models.DateTimeField(auto_now=True)

    objects = ProjectManager()

    def __str__(self):
        return self.name


class ProjectTeam(models.Model):
    """
    O sistema deve permitir se cadastrar e gerenciar os nomes dos membros da equipe do projeto.
    """
    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='team')
    name = models.CharField(max_length=140)

    def __str__(self):
        return self.name


class ProjectIndicator(models.Model):
    """
    O sistema deve permitir associar indicadores a serem acompanhados em um projeto. Ao associar um
    indicador ao projeto, deve ser possível informar os valores esperados mínimo e máximo para o mesmo.
    """

    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='indicators')
    indicator = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    max_value = models.PositiveIntegerField()
    min_value = models.PositiveIntegerField()


class ProjectIndicatorMonitor(models.Model):
    """
    O sistema deve permitir informar um indicador de um projeto a qualquer momento. Os indicadores devem
    ser associados a fases do projeto.
    """

    PHASE_CHOICES = (
        (1, 'Iniciação'),  # em análise, análise realizada, análise aprovada, 
        (2, 'Planejamento'),  # iniciado, planejado
        (3, 'Execução'),  # em andamento
        (4, 'Finalização')  # encerrado
    )

    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='indicator_monitor')
    indicator = models.ForeignKey(Indicator, on_delete=models.CASCADE)
    phase = models.PositiveSmallIntegerField(choices=PHASE_CHOICES)
    value = models.PositiveIntegerField()


class ProjectStatusMonitor(models.Model):
    """
    O sistema deve permitir alterar o status dos projetos. Ao alterar o status do projeto para 'análise
    aprovada', o sistema deve exigir o preenchimento de uma justificativa assim como na transição para o
    status 'cancelado'. A cada alteração de status, o sistema deve registrar o último responsável e data da
    alteração.
    """

    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='status_monitor')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(null=True)
    status = models.PositiveSmallIntegerField(choices=Project.STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)


class ProjectFollowUp(models.Model):
    """
    O sistema deve exigir que, para projetos de alto risco, seja registrado o acompanhamento semanal do projeto. 
    """

    project = models.ForeignKey(
        Project, on_delete=models.CASCADE, related_name='follow_ups')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    created = models.DateField(default=timezone.now)

projects/forms.py
import datetime
from django import forms
from django.contrib.auth.models import User

from .models import (Project, ProjectFollowUp, ProjectIndicator,
                     ProjectIndicatorMonitor, ProjectStatusMonitor, ProjectTeam)
from indicators.models import Indicator
from activities.models import Activity


class NewProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['name', 'description', 'manager', 'leader', 'start_date',
                  'forecast_finish_date', 'budget', 'rating']
        labels = {
            'name': ('Nome'),
            'description': ('Descrição'),
            'manager': ('Gerente'),
            'leader': ('Líder do Projeto'),
            'start_date': ('Data de Início'),
            'forecast_finish_date': ('Previsão de Término'),
            'budget': ('Orçamento'),
            'rating': ('Classificação')
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['manager'].queryset = User.objects.filter(
            is_active=True).order_by('username')
        self.fields['leader'].queryset = User.objects.filter(
            is_active=True).order_by('username')
        self.fields['rating'].choices = Project.RATING_CHOICES

    def clean_name(self):
        cleaned_data = super(NewProjectForm, self).clean()

        data = cleaned_data.get('name')

        n = Project.objects.filter(name=data)

        if n.exists():
            raise forms.ValidationError('Nome do Projeto já está sendo usado.')

        return data

    def clean_start_date(self):
        cleaned_data = super(NewProjectForm, self).clean()

        data = cleaned_data.get('start_date')

        if datetime.datetime.today().strftime('%d/%m/%Y') > data.strftime('%d/%m/%Y'):
            raise forms.ValidationError('Escolha uma data válida')

        return data

    def clean_forecast_finish_date(self):
        cleaned_data = super(NewProjectForm, self).clean()

        data = cleaned_data.get('forecast_finish_date')

        if cleaned_data.get('start_date') > data:
            raise forms.ValidationError(
                'A previsão de término não pode ser menor que a data de início do projeto.')

        return data


class UpdateProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['description', 'manager', 'leader', 'start_date',
                  'forecast_finish_date', 'budget', 'rating']
        labels = {
            'name': ('Nome'),
            'description': ('Descrição'),
            'manager': ('Gerente'),
            'leader': ('Líder do Projeto'),
            'start_date': ('Data de Início'),
            'forecast_finish_date': ('Previsão de Término'),
            'budget': ('Orçamento'),
            'rating': ('Classificação')
        }

    
    def clean_start_date(self):
        cleaned_data = super(UpdateProjectForm, self).clean()

        data = cleaned_data.get('start_date')

        if datetime.datetime.today().strftime('%d/%m/%Y') > data.strftime('%d/%m/%Y'):
            raise forms.ValidationError('Escolha uma data válida')

        return data

    def clean_forecast_finish_date(self):
        cleaned_data = super(UpdateProjectForm, self).clean()

        data = cleaned_data.get('forecast_finish_date')

        if cleaned_data.get('start_date') > data:
            raise forms.ValidationError(
                'A previsão de término não pode ser menor que a data de início do projeto.')

        return data


class NewProjectMemberForm(forms.ModelForm):

    class Meta:

        model = ProjectTeam
        fields = ['name']
        labels = {
            'name': ('Nome'),
        }


class ConnectProjectIndicatorForm(forms.ModelForm):

    class Meta:

        model = ProjectIndicator
        fields = ['indicator', 'max_value', 'min_value']
        labels = {
            'indicator': ('Indicador'),
            'max_value': ('Valor Máximo'),
            'min_value': ('Valor Mínimo'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['indicator'].queryset = Indicator.objects.filter(
            is_active=True).order_by('name')

    def clean(self):
        cleaned_data = super(ConnectProjectIndicatorForm, self).clean()

        max_value = cleaned_data.get('max_value')
        min_value = cleaned_data.get('min_value')

        if min_value > max_value:
            raise forms.ValidationError(
                'Valor Mínimo não pode superar o Máximo.')

    #TODO Validar se o indicador já existe


class MonitorProjectIndicatorForm(forms.ModelForm):

    class Meta:

        model = ProjectIndicatorMonitor
        fields = ['value']
        labels = {
            'value': ('Valor'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class NewProjectActivityForm(forms.ModelForm):

    class Meta:

        model = Activity
        fields = ['name', 'description', 'budget']
        labels = {
            'name': ('Nome'),
            'description': ('Descrição'),
            'budget': ('Orçamento'),
        }


class ProjectCancelForm(forms.ModelForm):

    class Meta:

        model = ProjectStatusMonitor
        fields = ['description']
        labels = {
            'description': ('Justificativa'),
        }


class NewProjectFollowUpForm(forms.ModelForm):

    class Meta:

        model = ProjectFollowUp
        fields = ['description']
        labels = {
            'description': ('Acompanhamento'),
        }

projects/templates/projects/project_add_activity.html
{% extends 'base.html' %} 

{% load widget_tweaks %}

{% block title %}Adicionar Atividade{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item">
  <a href="{% url 'project:index' %}">Projetos</a>
</li>
<li class="breadcrumb-item active">Adiconar Atividade</li>
{% endblock %} 

{% block content %}
<form method="post" novalidate>
  {% csrf_token %} 
  
  {% include 'includes/form.html' %}

  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
{% endblock %}

projects/templates/projects/project_add_followup.html
{% extends 'base.html' %} 

{% load widget_tweaks %}

{% block title %}Adicionar Membro{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item">
  <a href="{% url 'project:index' %}">Projetos</a>
</li>
<li class="breadcrumb-item active">Adiconar Acompanhamento</li>
{% endblock %} 

{% block content %}
<form method="post" novalidate>
  {% csrf_token %} 
  
  {% include 'includes/form.html' %}

  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
{% endblock %}

projects/templates/projects/project_add_member.html
{% extends 'base.html' %} 

{% load widget_tweaks %}

{% block title %}Adicionar Membro{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item">
  <a href="{% url 'project:index' %}">Projetos</a>
</li>
<li class="breadcrumb-item active">Adiconar Membro</li>
{% endblock %} 

{% block content %}
<form method="post" novalidate>
  {% csrf_token %} 
  
  {% include 'includes/form.html' %}

  <button type="submit" class="btn btn-success">Cadastrar</button>
</form>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends 'base.html' %} 

{% load static project_tags %}

{% block breadcrumb %}
<li class="breadcrumb-item">
    <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item">
    <a href="{% url 'project:index' %}">Projetos</a>
</li>
<li class="breadcrumb-item active">{{ project.name }}</li>
{% endblock %} 

{% block content %}

<div class="btn-toolbar mb-2 d-none d-md-block" role="toolbar" aria-label="Toolbar with button groups">
    <div class="btn-group mr-2" role="group" aria-label="First group">
        <a class="btn btn-secondary" href="{% url 'project:update' pk=project.pk %}">Editar Projeto</a>
    </div>
    <div class="btn-group mb-xs-2 mr-2" role="group" aria-label="First group">
        <a class="btn btn-secondary" href="{% url 'project:connect_indicator' pk=project.pk %}">Associar Indicador</a>
    </div>
    <div class="btn-group mb-xs-2 mr-2" role="group" aria-label="First group">
        <a class="btn btn-secondary" href="{% url 'project:add_activity' pk=project.pk %}">Adicionar Atividade</a>
    </div>
    <div class="btn-group mr-2" role="group" aria-label="First group">
        <a class="btn btn-secondary" href="{% url 'project:add_member' pk=project.pk %}">Adcionar Membro</a>
    </div>
    <div class="btn-group mr-2" role="group" aria-label="First group">
        <a class="btn btn-danger" href="{% url 'project:delete' pk=project.pk %}">Excluir Projeto</a>
    </div>
</div>

<!--Grupo de botoes para as telas pequenas-->
<div class="btn-group mb-2 d-md-none" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        Ações
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        <a class="btn btn-secondary dropdown-item" href="{% url 'project:update' pk=project.pk %}">Editar Projeto</a>
        <a class="btn btn-secondary dropdown-item" href="{% url 'project:connect_indicator' pk=project.pk %}">Associar Indicador</a>
        <a class="btn btn-secondary dropdown-item" href="{% url 'project:add_activity' pk=project.pk %}">Adicionar Atividade</a>
        <a class="btn btn-secondary dropdown-item" href="{% url 'project:add_member' pk=project.pk %}">Adcionar Membro</a>
        <a class="btn btn-danger dropdown-item" href="{% url 'project:delete' pk=project.pk %}">Excluir Projeto</a>
    </div>
</div>

<div class="card">

    <!--Cabecalho com as abas-->
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="project-tab" data-toggle="tab" href="#project" role="tab" aria-controls="home" aria-selected="true">Projeto</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="complementary-tab" data-toggle="tab" href="#complementary" role="tab" aria-controls="complementary" aria-selected="false">Informações Complementares</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="status-history-tab" data-toggle="tab" href="#status-history" role="tab" aria-controls="status-history" aria-selected="false">Histórico de Status</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="activity-tab" data-toggle="tab" href="#activity" role="tab" aria-controls="activity" aria-selected="false">Atividades</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="followup-tab" data-toggle="tab" href="#followup" role="tab" aria-controls="followup" aria-selected="false">Acompanhamentos</a>
            </li>
        </ul>
    </div>

    <div class="card-body">
        <div class="tab-content" id="myTabContent">

            <!-- Aba do Projeto -->
            <div class="tab-pane fade show active" id="project" role="tabpanel" aria-labelledby="project-tab">
                <h5 class="card-title">{{ project.name }}
                    <span class="badge badge-{{ project|get_rating_css_class }}">{{ project.get_rating_display }}</span>
                    <span class="badge badge-{{ project|get_status_css_class }}">{{ project.get_status_display }}</span>
                </h5>
                <h6 class="card-subtitle mb-2 text-muted">Última atualização - {{ project.modified }}</h6>

                <dl class="row">
                    <dt class="col-sm-3 col-md-2">Gerente Responsável</dt>
                    <dd class="col-md-9">{{ project.manager.get_full_name }}</dd>
                    <dt class="col-sm-3 col-md-2">Líder do Projeto</dt>
                    <dd class="col-md-9">{{ project.leader.get_full_name }}</dd>

                    <dt class="col-sm-2 col-md-2">Datas</dt>
                    <dd class="col-sm-10 col-md-10">
                        <dl class="row">
                            <dt class="col-sm-3 col-md-2">Início</dt>
                            <dd class="col-sm-9 col-md-10">{{ project.start_date|date:"d/m/y" }}</dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-3 col-md-2">Previsão de Término</dt>
                            <dd class="col-sm-9 col-md-10">{{ project.forecast_finish_date|date:"d/m/y" }}</dd>
                        </dl>
                        <dl class="row">
                            <dt class="col-sm-3 col-md-2">Término Real</dt>
                            <dd class="col-sm-9 col-md-10">{{ project.end_date|date:"d/m/y" }}</dd>
                        </dl>
                    </dd>

                    <dt class="col-sm-2 col-md-2">Orçamento</dt>
                    <dd class="col-sm-10 col-md-10">R$ {{ project.budget }}</dd>

                    <dt class="col-sm-2 col-md-2">Descrição</dt>
                    <dd class="col-sm-10 col-md-10 text-justify">{{ project.description }}</dd>
                </dl>

            </div>

            <!-- Aba do Complemento -->
            <div class="tab-pane fade show" id="complementary" role="tabpanel" aria-labelledby="complementary-tab">
                <div class="card-deck">

                    <!-- Indicadores -->
                    <div class="card">
                        <div class="card-header">
                            Indicadores
                        </div>
                        <ul class="list-group list-group-flush"  id="indicator-list">
                            {% include 'projects/includes/partial_indicator_list.html' %}
                        </ul>
                    </div>

                    <!-- Equipe -->
                    <div class="card">
                        <div class="card-header">
                            Equipe
                        </div>
                        <ul class="list-group list-group-flush" id="team-list">
                            {% include 'projects/includes/partial_team_list.html' %}
                        </ul>
                    </div>

                </div>

            </div>

            <!-- Aba do Historico do status -->
            <div class="tab-pane fade" id="status-history" role="tabpanel" aria-labelledby="status-history-tab">

                <h3>
                    {% ifequal project.status 1 %}
                    Em Análise                    
                    <small class="text-muted">Análise Realizada</small>
                    {% endifequal %}

                    {% ifequal project.status 2 %}
                    Análise Realizada                    
                    <small class="text-muted">Análise Aprovada</small>
                    {% endifequal %}

                    {% ifequal project.status 3 %}
                    Análise Aprovada                   
                    <small class="text-muted">Iniciado</small>
                    {% endifequal %}

                    {% ifequal project.status 4 %}
                    Iniciado                    
                    <small class="text-muted">Planejado</small>
                    {% endifequal %}

                    {% ifequal project.status 5 %}
                    Planejado                   
                    <small class="text-muted">Em Andamento</small>
                    {% endifequal %}

                    {% ifequal project.status 6 %}
                    Em Andamento                    
                    <small class="text-muted">Encerrado</small>
                    {% endifequal %}

                    {% ifequal project.status 7 %}
                    Enderrado                 
                    {% endifequal %}
                </h3>
                
                {% if project.status|in_list:'1,2,3,4,5,6' %}
                <form action="{% url 'project:change_status' pk=project.pk %}" method="post">
                    {% csrf_token %}

                    {% ifequal project.status 2 %}
                    <div class="form-group">
                        <label for="description" class="control-label">Justificativa:</label>
                        <textarea class="form-control" id="description" rows="5" name="description" required></textarea>
                    </div>
                    {% endifequal %}
                    
                    <a class="btn btn-danger" href="{% url 'project:cancel' pk=project.pk %}">Cancelar Projeto</a>
                    <button type="submit" class="btn btn-primary">Atualizar Status</button>
                </form>
                {% endif %}


                <ul class="list-group list-group-flush mt-2">
                    {% for status in status_list %}
                    <li class="list-group-item">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">Alteração de Status feita por {{ status.user }}</h5>
                            <small>{{ status.created }}</small>
                        </div>
                        <p class="mb-1">{{ status.description|default_if_none:"--" }}</p>
                        <label class="font-weight-bold">Status:&nbsp;</label>
                        <span class="badge badge-{{ status|get_status_css_class }}">{{ status.get_status_display }}</span>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <!-- Aba das Atividades -->
            <div class="tab-pane fade" id="activity" role="tabpanel" aria-labelledby="activity-tab">

                <ul class="list-group list-group-flush">
                    {% for activity in activity_list %}
                    <li class="list-group-item">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">{{ activity.name }}</h5>
                            <a class="btn btn-sm btn-danger" href="{% url 'project:delete_activity' pk=activity.pk %}">Excluir</a>
                        </div>
                        <p class="mb-1">{{ activity.description }}</p>
                        <label class="font-weight-bold">Orçamento: R$ {{ activity.budget }}</label>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <!-- Aba do Acompanhamento -->
            <div class="tab-pane fade" id="followup" role="tabpanel" aria-labelledby="followup-tab">
            
                <ul class="list-group list-group-flush">
                    
                    {% for follow_up in follow_up_list %}
                    <li class="list-group-item">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1">Acompanhamento</h5>
                            <small>{{ follow_up.created|date:"d/m/Y" }}</small>
                        </div>
                        <p class="mb-1">{{ follow_up.description }}</p>
                        <label class="font-weight-bold">Usuário:&nbsp;</label>
                        {{ follow_up.user.username }}
                    </li>
                    {% endfor %}

                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

projects/templates/projects/project_list.html
{% extends 'base.html' %}

{% load widget_tweaks project_tags %}

{% block title %}Projetos{% endblock %} 

{% block breadcrumb %}
<li class="breadcrumb-item">
  <a href="{% url 'home' %}">Home</a>
</li>
<li class="breadcrumb-item active">Projetos</li>
{% endblock %} 

{% block content %}
<div class="mb-2 float-left">
    <a class="btn btn-success" href="{% url 'project:create' %}">Adicionar</a>
</div>

<div class="mb-2 float-right">
    <form class="form-inline my-lg-0" action="{% url 'project:search' %}" method="GET">
        <input class="form-control mr-sm-2" type="text" placeholder="Pesquisar" aria-label="Search" name="q">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
</div>

<table class="table table-striped table-responsive-sm">
    <thead class="thead-dark">
        <tr>
            <th>Projeto</th>
            <th>Gerente</th>
            <th>Orçamento</th>
            <th>Classificação de Risco</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for project in project_list %}
        <tr>
            <td><a href="{% url 'project:detail' pk=project.pk %}">{{ project.name }}</a></td>
            <td>{{ project.manager }}</td>
            <td>R$ {{ project.budget }}</td>
            <td><span class="badge badge-{{ project|get_rating_css_class }}">{{ project.get_rating_display }}</span></td>
            <td><span class="badge badge-{{ project|get_status_css_class }}">{{ project.get_status_display }}</span></td>
        </tr>
        {% endfor %}              
    </tbody>
</table>

{% include 'includes/pagination.html' %}

{% endblock %}