reports/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^indicator$', views.report_project_by_indicator, name='by_indicator'),
    url(r'^status$', views.report_project_by_status, name='by_status'),
    url(r'^phase$', views.report_project_by_phase, name='by_phase'),
]

sgpp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^project/', include('projects.urls', namespace='project')),
    url(r'^indicator/', include('indicators.urls', namespace='indicator')),
    url(r'^report/', include('reports.urls', namespace='report')),
    url(r'^admin/', admin.site.urls),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}SGPP{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block stylesheet %}{% endblock %}
</head>

<body>
    {% block body %}
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">SGPP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav ml-auto">

            <!--Apenas mostra em telas pequenas-->
            <div class="d-sm-none">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'project:index' %}">Projetos</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'indicator:index' %}">Indicadores</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'report:index' %}">Relatórios</a>
              </li>
            </div>


            <li class="nav-item dropdown">
              <div class="dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                  <a class="dropdown-item" href="#">Último login - {{ user.last_login|date:"d/m/y H:i"}}</a>
                  <a class="dropdown-item" href="#">Mudar senha</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>
              </div>
            </li>
          </ul>
          
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        
        <!--Apenas mostra em telas maiores-->
        <div class="col-sm-2 col-md-2 d-none d-sm-block my-4">
        {% block navbar %}
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'project:index' %}">Projetos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'indicator:index' %}">Indicadores</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'report:index' %}">Relatórios</a>
          </li>
        </ul>
        {% endblock %}
        </div>        

        <div class="col-12 col-sm-10 col-md-10">
          {% if messages %}
          <br/>
            {% for message in messages %}
          <div class="alert alert-info alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Aviso!</h4>
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>          
            {% endfor %}
          {% endif %}

          <ol class="breadcrumb my-4">
            {% block breadcrumb %}
            {% endblock %}
          </ol>
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    {% endblock body %}

  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script>
    $( document ).ready(function() {
        //fecha o aviso automaticamente apos 4 segundos
        $(".alert").delay(4000).slideUp(500, function() {
            $(this).alert('close');
        });
    });   
  </script>
  
  {% block javascript %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Bem Vindo</h1>
        <p class="lead">Esta é uma ferramenta para reunir, integrar e disseminar os resultados e informações do gerenciamento de projetos da empresa</p>
    </div>
</div>
{% endblock %}